### NAVIGATION ###

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    default_nav_to_pose_bt_xml: /behaviors/navigate_pose.xml
    default_nav_through_poses_bt_xml: /behaviors/navigate_poses.xml
    robot_base_frame: base_link
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    FollowPath:
          plugin: "nav2_mppi_controller::MPPIController"
          time_steps: 100
          model_dt: 0.10
          batch_size: 3000
          vx_std: 0.3
          vy_std: 0.2
          wz_std: 0.4
          vx_max: 2.0
          vx_min: -0.35
          vy_max: 1.5
          wz_max: 1.9
          iteration_count: 1
          prune_distance: 1.7
          transform_tolerance: 0.1
          temperature: 0.3
          gamma: 0.01
          motion_model: "DiffDrive"
          visualize: false
          reset_period: 1.0 # (only in Humble)
          TrajectoryVisualizer:
            trajectory_step: 5
            time_step: 3
          AckermannConstrains:
            min_turning_r: 0.01
          critics: ["ConstraintCritic", "ObstaclesCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
          ConstraintCritic:
            enabled: true
            cost_power: 1
            cost_weight: 4.0
          GoalCritic:
            enabled: true
            cost_power: 1
            cost_weight: 5.0
            threshold_to_consider: 1.4
          GoalAngleCritic:
            enabled: true
            cost_power: 1
            cost_weight: 3.0
            threshold_to_consider: 0.5
          PreferForwardCritic:
            enabled: true
            cost_power: 1
            cost_weight: 5.0
            threshold_to_consider: 0.5
          ObstaclesCritic:
            enabled: true
            cost_power: 1
            repulsion_weight: 1.5
            critical_weight: 20.0
            consider_footprint: false
            collision_cost: 10000.0
            collision_margin_distance: 0.01
            near_goal_distance: 0.5
            inflation_radius: 0.561 # (only in Humble)
            cost_scaling_factor: 12.58 # (only in Humble)
          PathAlignCritic:
            enabled: true
            cost_power: 1
            cost_weight: 14.0
            max_path_occupancy_ratio: 0.05
            trajectory_point_step: 3
            threshold_to_consider: 0.5
            offset_from_furthest: 20
            use_path_orientations: true 
          PathFollowCritic:
            enabled: true
            cost_power: 1
            cost_weight: 5.0
            offset_from_furthest: 5
            threshold_to_consider: 1.4
          PathAngleCritic:
            enabled: true
            cost_power: 1
            cost_weight: 2.0
            offset_from_furthest: 4
            threshold_to_consider: 0.5
            max_angle_to_furthest: 1.0
            mode: 0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False

      global_frame: odom
      robot_base_frame: base_link

      update_frequency: 5.0
      publish_frequency: 2.0

      width: 5
      height: 5
      resolution: 0.05

      always_send_full_costmap: True
      rolling_window: True

      footprint: "[[0.4826, 0.385], [0.48265, -0.385], [-0.48, -0.385], [-0.48, 0.385]]"
      footprint_padding: 0.01

      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: scan
        scan:
          topic: /velodyne_points
          min_obstacle_height: 0.2
          max_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.0
          obstacle_min_range: 0.25
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 3.0
        inflation_radius: 1.5

  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False

      global_frame: map
      robot_base_frame: base_link

      update_frequency: 1.0
      publish_frequency: 1.0

      resolution: 0.05

      always_send_full_costmap: True
      track_unknown_space: True # if false, treats unknown space as free space, else as unknown space

      footprint: "[[0.4826, 0.385], [0.48265, -0.385], [-0.4826, -0.385], [-0.4826, 0.385]]"
      footprint_padding: 0.01

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        map_subscribe_transient_local: True
        map_topic: /map
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: scan
        scan:
          topic: /velodyne_points
          min_obstacle_height: 0.1
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 5.0
          obstacle_min_range: 0.25
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: True
        cost_scaling_factor: 3.0
        inflation_radius: 1.5

  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

planner_server:
  ros__parameters:
    use_sim_time: False

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125 # tolerance for planning if unable to reach exact pose, in meters
      downsample_costmap: False # whether or not to downsample the map
      downsampling_factor: 1 # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: true # allow traveling in unknown space
      max_iterations: 1000000 # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000 # maximum number of iterations to attempt to reach goal once in tolerance
      max_planning_time: 2.0 # max time in s for planner to plan, smooth
      motion_model_for_search: "MOORE" # 2D Moore, Von Neumann
      cost_travel_multiplier: 2.0 # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      use_final_approach_orientation: True # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    use_sim_time: False

    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 1.0 # 0.1

    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0

    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

    # spin & backup
    simulate_ahead_time: 2.0

    # spin
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

behavior_server:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: True
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

### LOCALIZATION ###

amcl:
  ros__parameters:
    use_sim_time: False

    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link

    scan_topic: scan

    # Galactic
    # robot_model_type: differential
    # Humble
    robot_model_type: nav2_amcl::DifferentialMotionModel

    set_initial_pose: True
    always_reset_initial_pose: True
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

    tf_broadcast: True
    transform_tolerance: 1.0

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.2

    # Beam skipping - ignores beams for which a majoirty of particles do not agree with the map
    # prevents correct particles from getting down weighted because of unexpected obstacles
    # such as humans
    do_beamskip: False
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    lambda_short: 0.1

    laser_model_type: likelihood_field
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: -1.0

    max_beams: 60

    max_particles: 25000
    min_particles: 6000

    pf_err: 0.05
    pf_z: 0.99

    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    resample_interval: 1
    save_pose_rate: 0.5
    sigma_hit: 0.2

    update_min_a: 0.1
    update_min_d: 0.15

    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

### MAP SERVER ###

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"